# Generated by Django 5.1.4 on 2025-02-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="crop_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
